### ISSUE TITLE
Please add Argo to the mix!

### ISSUE THREAD

**Issue by eimantas** [bwhiteley/JSONShootout#1]
What the title says. Made by thoughtbot. Find here: [Argo](https://github.com/thoughtbot/Argo)

**Comment by bwhiteley** [comment]
I added it to the performance graph. 
https://raw.githubusercontent.com/bwhiteley/JSONShootout/master/images/performance.png

I had to butcher the project so badly just to get it to work, I don't know if I'll commit it to master.
