### ISSUE TITLE
Please add Freddy for comparison

### ISSUE THREAD

**Issue by ebarrenechea** [bwhiteley/JSONShootout#10]
https://github.com/bignerdranch/Freddy

**Comment by bwhiteley** [comment]
You're welcome to submit a pull request to add a new framework. 
Please see the Contributing section at the bottom of the Readme.

Note that the project may become untenable as more frameworks are added. Often the syntax changes for a given framework. When the dependencies are updated while adding a new framework, existing code may no longer compile.

**Comment by shams-ahmed** [comment]
@bwhiteley Carthage support versioning requirement so you could limit the scope and management by making this a requirement. see there [doc](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement)

**Comment by bwhiteley** [comment]
@shams-ahmed yes, that could help.
