### ISSUE TITLE
ObjectMapper

### ISSUE THREAD

**Issue by vincentsaluzzo** [bwhiteley/JSONShootout#13]
This comparaison are good, but you miss for me the better solution for converting JSON <-> Data Model in two way

You should add this solution to your test case : https://github.com/Hearst-DD/ObjectMapper

**Comment by ManWithBear** [comment]
Sent pull request: https://github.com/bwhiteley/JSONShootout/pull/14

**Comment by bwhiteley** [comment]
I merged support for ObjectMapper and updated the performance graph.
