### ISSUE TITLE
PMJSON

### ISSUE THREAD

**Issue by lilyball** [bwhiteley/JSONShootout#22]
There's a second pure-swift JSON parser which has been around for a while, which is my very own [PMJSON](https://github.com/postmates/PMJSON). I'd love to see it included in the shootout.

**Comment by bwhiteley** [comment]
Hi Kevin. PMJSON looks pretty cool. 

Feel free to add support for PMJSON and submit a pull request. Look at the Contributing section of the README. 

Thanks.
