### ISSUE TITLE
Explanation for the perf difference between Marshal and Mapper

### ISSUE THREAD

**Issue by Noobish1** [bwhiteley/JSONShootout#24]
Hey there, thought you might be interested in this: 

All the performance difference between Marshal and Mapper is because of this one commit: https://github.com/lyft/mapper/commit/84b7fb424bcf53e2cbd80a3eeba0f5e844390ffb.

Basically they use their own `value(forKeyPath:)` function so they don't get exceptions for type mismatches.

I'm not saying this is good or bad, just interesting.

**Comment by bwhiteley** [comment]
Correct.
