### ISSUE TITLE
Where is graph of NSJSONSerialisation?

### ISSUE THREAD

**Issue by axello** [bwhiteley/JSONShootout#28]
Before I pull and run the tests myself, in the article you state:

"This graph shows time spent in each of the mappers as well as time spent in NSJSONSerialization for a reference."

However, I do not see this data point anywhere in the graph... Please help me if I'm too near-sighted to see it.

**Comment by bwhiteley** [comment]
The red portion of the bars represents the time taken to deserialize in
NSJSONSerialization, and the blue portion of the bars represents mapping
from Dictionaries to model objects.
